#!/bin/bash
# -----------------------------------------------------------------------------
# File: monitor-menu.sh
# Author: Naveen Duhan
# Description: Rofi menu for monitor management with smart auto-detect.
#              - DP monitors: External Only (disable laptop, work on big screen)
#              - HDMI monitors: Extend Above (HDMI on top, laptop below)
#              - No external: Laptop Only
#              - Disconnect: Auto-switch back to laptop
#              Rofi menu allows manual override.
# -----------------------------------------------------------------------------

CONFIG_FILE="$HOME/.config/hypr/monitors.conf"
BACKUP_FILE="$HOME/.config/hypr/monitors.conf.bak"

# Create backup if it doesn't exist
if [ ! -f "$BACKUP_FILE" ]; then
	if [ -f "$CONFIG_FILE" ]; then
		cp "$CONFIG_FILE" "$BACKUP_FILE"
	else
		echo "# Auto-generated backup
monitor=eDP-1,preferred,auto,1.25" >"$BACKUP_FILE"
	fi
fi

# Internal monitor name
INTERNAL="eDP-1"

# Function to get current monitors
get_monitors() {
	hyprctl monitors all -j 2>/dev/null
}

# Function to find external monitor (any non-eDP-1)
get_external() {
	echo "$1" | jq -r '.[] | select(.name != "eDP-1") | .name' | head -n1
}

# Function to get monitor height
get_monitor_height() {
	local mon_name="$1"
	local monitors_json="$2"
	echo "$monitors_json" | jq -r ".[] | select(.name == \"$mon_name\") | .height" 2>/dev/null
}

# Function to restart waybar
restart_waybar() {
	killall waybar 2>/dev/null
	sleep 0.3
	waybar &
}

# Function to apply config and reload
apply_config() {
	local config="$1"
	echo -e "$config" >"$CONFIG_FILE"
	hyprctl reload 2>/dev/null
	sleep 0.5
	restart_waybar
}

# Function: Laptop Only
setup_laptop_only() {
	local config="# Auto-generated by monitor-menu.sh
# Mode: Laptop Only

monitor=$INTERNAL,preferred,auto,1.25
"
	apply_config "$config"
	hyprctl dispatch focusmonitor "$INTERNAL" 2>/dev/null
	hyprctl dispatch workspace 1 2>/dev/null
	notify-send "Monitor" "Laptop Only"
}

# Function: External Only (for DP monitors)
setup_external_only() {
	local external="$1"
	local config="# Auto-generated by monitor-menu.sh
# Mode: External Only ($external)

monitor=$INTERNAL,disable
monitor=$external,preferred,auto,1
"
	apply_config "$config"
	hyprctl dispatch focusmonitor "$external" 2>/dev/null
	hyprctl dispatch workspace 1 2>/dev/null
	notify-send "Monitor" "External Only ($external)"
}

# Function: Extend Above (for HDMI monitors)
setup_extend_above() {
	local external="$1"
	local monitors_json="$2"

	# Get external monitor height to position laptop below it
	local ext_h=$(get_monitor_height "$external" "$monitors_json")
	ext_h=${ext_h:-1080} # Default to 1080 if not detected

	local config="# Auto-generated by monitor-menu.sh
# Mode: Extend Above ($external on top, $INTERNAL below)

monitor=$external,preferred,0x0,1
monitor=$INTERNAL,preferred,0x${ext_h},1.25
"
	apply_config "$config"
	hyprctl dispatch focusmonitor "$INTERNAL" 2>/dev/null
	hyprctl dispatch workspace 1 2>/dev/null
	notify-send "Monitor" "Extend Above ($external on top)"
}

# Function: Extend Right
setup_extend_right() {
	local external="$1"
	local config="# Auto-generated by monitor-menu.sh
# Mode: Extend Right ($external to the right of $INTERNAL)

monitor=$INTERNAL,preferred,0x0,1.25
monitor=$external,preferred,auto-right,1
"
	apply_config "$config"
	hyprctl dispatch focusmonitor "$INTERNAL" 2>/dev/null
	hyprctl dispatch workspace 1 2>/dev/null
	notify-send "Monitor" "Extend Right"
}

# Function: Extend Left
setup_extend_left() {
	local external="$1"
	local config="# Auto-generated by monitor-menu.sh
# Mode: Extend Left ($external to the left of $INTERNAL)

monitor=$external,preferred,0x0,1
monitor=$INTERNAL,preferred,auto-right,1.25
"
	apply_config "$config"
	hyprctl dispatch focusmonitor "$INTERNAL" 2>/dev/null
	hyprctl dispatch workspace 1 2>/dev/null
	notify-send "Monitor" "Extend Left"
}

# Function: Mirror
setup_mirror() {
	local external="$1"
	local monitors_json="$2"

	# Get widths to determine master
	local int_w=$(echo "$monitors_json" | jq -r ".[] | select(.name == \"$INTERNAL\") | .width" 2>/dev/null)
	local ext_w=$(echo "$monitors_json" | jq -r ".[] | select(.name == \"$external\") | .width" 2>/dev/null)
	int_w=${int_w:-0}
	ext_w=${ext_w:-0}

	local config="# Auto-generated by monitor-menu.sh
# Mode: Mirror

"
	if [ "$ext_w" -gt "$int_w" ]; then
		# External is higher res - make it master
		config+="monitor=$external,preferred,auto,1
monitor=$INTERNAL,preferred,auto,1.25,mirror,$external
"
	else
		# Internal is higher res - make it master
		config+="monitor=$INTERNAL,preferred,auto,1.25
monitor=$external,preferred,auto,1,mirror,$INTERNAL
"
	fi

	apply_config "$config"
	notify-send "Monitor" "Mirror Mode"
}

# Function: Smart auto-detect and configure
setup_auto() {
	local monitors_json=$(get_monitors)
	local external=$(get_external "$monitors_json")

	if [ -z "$external" ]; then
		# No external monitor - laptop only
		setup_laptop_only
	elif [[ "$external" == DP-* ]]; then
		# DP monitor - external only (disable laptop)
		setup_external_only "$external"
	elif [[ "$external" == HDMI-* ]]; then
		# HDMI monitor - extend above
		setup_extend_above "$external" "$monitors_json"
	else
		# Unknown type - default to laptop only
		setup_laptop_only
	fi
}

# If called with "auto" argument - smart auto-detect with polling
if [ "$1" = "auto" ]; then
	# Wait for Hyprland to be ready on startup
	sleep 1

	# Initial setup
	setup_auto

	# Poll for monitor changes every 2 seconds
	PREVIOUS_MONITORS=""
	while true; do
		sleep 2
		CURRENT_MONITORS=$(hyprctl monitors all -j 2>/dev/null | jq -r '.[].name' | sort | tr '\n' ',' 2>/dev/null)

		if [ "$CURRENT_MONITORS" != "$PREVIOUS_MONITORS" ] && [ -n "$CURRENT_MONITORS" ]; then
			PREVIOUS_MONITORS="$CURRENT_MONITORS"
			setup_auto
		fi
	done

	exit 0
fi

# If called with specific mode argument
case "$1" in
"mirror")
	monitors_json=$(get_monitors)
	external=$(get_external "$monitors_json")
	[ -n "$external" ] && setup_mirror "$external" "$monitors_json" || notify-send "Monitor" "No external monitor"
	exit 0
	;;
"extend-right")
	monitors_json=$(get_monitors)
	external=$(get_external "$monitors_json")
	[ -n "$external" ] && setup_extend_right "$external" || notify-send "Monitor" "No external monitor"
	exit 0
	;;
"extend-left")
	monitors_json=$(get_monitors)
	external=$(get_external "$monitors_json")
	[ -n "$external" ] && setup_extend_left "$external" || notify-send "Monitor" "No external monitor"
	exit 0
	;;
"extend-above")
	monitors_json=$(get_monitors)
	external=$(get_external "$monitors_json")
	[ -n "$external" ] && setup_extend_above "$external" "$monitors_json" || notify-send "Monitor" "No external monitor"
	exit 0
	;;
"external-only")
	monitors_json=$(get_monitors)
	external=$(get_external "$monitors_json")
	[ -n "$external" ] && setup_external_only "$external" || notify-send "Monitor" "No external monitor"
	exit 0
	;;
"laptop-only")
	setup_laptop_only
	exit 0
	;;
esac

# No argument or unknown - show Rofi menu
monitors_json=$(get_monitors)
external=$(get_external "$monitors_json")

# Build Rofi Options
OPTIONS="🖥️ Extend Right
🖥️ Extend Left
🖥️ Extend Above
🪞 Mirror
📺 External Only
💻 Laptop Only
🔄 Reset to Default"

CHOICE=$(echo -e "$OPTIONS" | rofi -dmenu -p "Monitor" -theme-str 'window {width: 300px;}')

[ -z "$CHOICE" ] && exit 0

case "$CHOICE" in
"🖥️ Extend Right")
	[ -n "$external" ] && setup_extend_right "$external" || notify-send "Monitor" "No external monitor detected"
	;;
"🖥️ Extend Left")
	[ -n "$external" ] && setup_extend_left "$external" || notify-send "Monitor" "No external monitor detected"
	;;
"🖥️ Extend Above")
	[ -n "$external" ] && setup_extend_above "$external" "$monitors_json" || notify-send "Monitor" "No external monitor detected"
	;;
"🪞 Mirror")
	[ -n "$external" ] && setup_mirror "$external" "$monitors_json" || notify-send "Monitor" "No external monitor detected"
	;;
"📺 External Only")
	[ -n "$external" ] && setup_external_only "$external" || notify-send "Monitor" "No external monitor detected"
	;;
"💻 Laptop Only")
	setup_laptop_only
	;;
"🔄 Reset to Default")
	cat "$BACKUP_FILE" >"$CONFIG_FILE"
	hyprctl reload
	restart_waybar
	notify-send "Monitor" "Config Reset to Default"
	;;
esac
