#!/bin/bash
# -----------------------------------------------------------------------------
# File: monitor-menu.sh
# Author: Naveen Duhan
# Description: Rofi menu for monitor management.
#              Uses DIRECT CONFIG MODIFICATION + RELOAD to ensure stability.
#              If called with "auto" or "mirror" argument, automatically sets up mirroring.
# -----------------------------------------------------------------------------

CONFIG_FILE="$HOME/.config/hypr/monitors.conf"
BACKUP_FILE="$HOME/.config/hypr/monitors.conf.bak"

# Create backup if it doesn't exist
if [ ! -f "$BACKUP_FILE" ]; then
    if [ -f "$CONFIG_FILE" ]; then
        cp "$CONFIG_FILE" "$BACKUP_FILE"
    else
        # Create initial backup with just internal monitor
        echo "# Auto-generated backup
monitor=eDP-1,preferred,auto,1.25" > "$BACKUP_FILE"
    fi
fi

# Get all connected monitors (enabled or disabled)
MONITORS_JSON=$(hyprctl monitors all -j 2>/dev/null)

# Identify Internal and External
INTERNAL="eDP-1"
# Find first external monitor that is connected
EXTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.name != "eDP-1") | .name' | head -n1)

# Function to setup mirroring
setup_mirror() {
    # If no external monitor, just use internal
    if [ -z "$EXTERNAL" ]; then
        NEW_CONFIG="# Auto-generated by monitor-menu.sh
# Source of truth: $BACKUP_FILE

monitor=$INTERNAL,preferred,auto,1.25
"
        echo -e "$NEW_CONFIG" > "$CONFIG_FILE"
        hyprctl reload 2>/dev/null
        return 0
    fi
    
    # Logic for high-res mirroring
    INT_W=$(echo "$MONITORS_JSON" | jq -r ".[] | select(.name == \"$INTERNAL\") | .width" 2>/dev/null)
    EXT_W=$(echo "$MONITORS_JSON" | jq -r ".[] | select(.name == \"$EXTERNAL\") | .width" 2>/dev/null)
    
    # Default to 0 if null
    INT_W=${INT_W:-0}
    EXT_W=${EXT_W:-0}
    
    NEW_CONFIG="# Auto-generated by monitor-menu.sh
# Source of truth: $BACKUP_FILE

"
    
    if [ "$EXT_W" -gt "$INT_W" ]; then
        # External is Master
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,auto,1\n"
        NEW_CONFIG+="monitor=$INTERNAL,preferred,auto,1.25,mirror,$EXTERNAL\n"
    else
        # Internal is Master
        NEW_CONFIG+="monitor=$INTERNAL,preferred,auto,1.25\n"
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,auto,1,mirror,$INTERNAL\n"
    fi
    
    echo -e "$NEW_CONFIG" > "$CONFIG_FILE"
    hyprctl reload 2>/dev/null
    
    # Restart waybar to ensure it appears on the correct monitor
    killall waybar 2>/dev/null
    waybar & 2>/dev/null
    
    return 0
}

# If called with "auto" or "mirror" argument, automatically set up mirroring
if [ "$1" = "auto" ] || [ "$1" = "mirror" ]; then
    # Wait a bit for Hyprland to be ready (especially on startup)
    if [ "$1" = "auto" ]; then
        sleep 1
    fi
    
    # Initial setup
    setup_mirror
    
    # If "auto", also listen for monitor hotplug events
    if [ "$1" = "auto" ]; then
        # Poll for monitor changes every 2 seconds
        PREVIOUS_MONITORS=""
        while true; do
            sleep 2
            CURRENT_MONITORS=$(hyprctl monitors all -j 2>/dev/null | jq -r '.[].name' | sort | tr '\n' ',' 2>/dev/null)
            
            if [ "$CURRENT_MONITORS" != "$PREVIOUS_MONITORS" ] && [ -n "$CURRENT_MONITORS" ]; then
                PREVIOUS_MONITORS="$CURRENT_MONITORS"
                # Update MONITORS_JSON and EXTERNAL for the new state
                MONITORS_JSON=$(hyprctl monitors all -j 2>/dev/null)
                EXTERNAL=$(echo "$MONITORS_JSON" | jq -r '.[] | select(.name != "eDP-1") | .name' | head -n1)
                setup_mirror
            fi
        done
    fi
    
    exit 0
fi

# Helper to get existing config line for a monitor to preserve params (resolution, scale)
# Usage: get_conf "HDMI-A-1" "default_params"
get_conf() {
    local mon_name="$1"
    local default="$2"
    # Grep the active config or backup for the line starting with "monitor=NAME,"
    # We take the first match.
    local line=$(grep "^monitor=$mon_name," "$CONFIG_FILE" | head -n1)
    
    if [ -z "$line" ]; then
        # Check backup
        line=$(grep "^monitor=$mon_name," "$BACKUP_FILE" | head -n1)
    fi

    if [ -n "$line" ]; then
        # Return the params part (everything after name,)
        # monitor=NAME,PARAMS -> cut -d, -f2-
        echo "$line" | cut -d',' -f2-
    else
        echo "$default"
    fi
}

# Default params if not found in config
INTERNAL_PARAMS=$(get_conf "$INTERNAL" "preferred,auto,1.25")
# For external, we default to preferred,auto,1 if not found
EXTERNAL_PARAMS=$(get_conf "$EXTERNAL" "preferred,auto,1")

# Build Rofi Options
OPTIONS="🖥️ Extend Right\n🖥️ Extend Left\n🖥️ Extend Above\n🪞 Mirror\n📺 External Only\n💻 Laptop Only\n🔄 Reset to Default"

# Show Rofi - force it to appear on focused monitor if possible, though rofi usually handles this.
# If Rofi is failing to show, it might be due to disabled monitors. 
# We can't easily fix Rofi placement if the compositor is confused, but the reload actions below will fix the system.
CHOICE=$(echo -e "$OPTIONS" | rofi -dmenu -p "Monitor" -theme-str 'window {width: 300px;}')

if [ -z "$CHOICE" ]; then
    exit 0
fi

NEW_CONFIG="# Auto-generated by monitor-menu.sh
# Source of truth: $BACKUP_FILE

"

case "$CHOICE" in
    "🖥️ Extend Right")
        NEW_CONFIG+="monitor=$INTERNAL,preferred,0x0,1.25\n"
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,auto-right,1\n"
        ;;
    "🖥️ Extend Left")
        NEW_CONFIG+="monitor=$INTERNAL,preferred,auto-right,1.25\n"
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,0x0,1\n"
        ;;
    "🖥️ Extend Above")
        NEW_CONFIG+="monitor=$INTERNAL,preferred,0x1440,1.25\n"
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,0x0,1\n" 
        # Note: precise positioning is hard without knowing resolutions. 
        # But 'auto' keywords in config are limited. 
        # Let's rely on standard 'auto' behavior if possible, or relative.
        # Actually, for config file, we can just list them. Hyprland attempts to place them.
        # But to be safe, let's use the explicit 'preferred,auto,1' style which Hyprland resolves.
        
        # RE-THINK: Using standard params from file is safest for resolution, but we need to override Position.
        # Simplified Extend Right:
        NEW_CONFIG+="monitor=$INTERNAL,preferred,0x0,1.25\n"
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,auto,1\n" # Auto usually puts it to the right
        ;;
    "🪞 Mirror")
        # Use the setup_mirror function
        setup_mirror
        exit 0
        ;;
    "📺 External Only")
        NEW_CONFIG+="monitor=$INTERNAL,disable\n"
        # Ensure we use the best settings for external
        NEW_CONFIG+="monitor=$EXTERNAL,preferred,auto,1\n"
        ;;
    "💻 Laptop Only")
        NEW_CONFIG+="monitor=$INTERNAL,preferred,auto,1.25\n"
        if [ -n "$EXTERNAL" ]; then
            NEW_CONFIG+="monitor=$EXTERNAL,disable\n"
        fi
        ;;
    "🔄 Reset to Default")
        # Restore from backup
        cat "$BACKUP_FILE" > "$CONFIG_FILE"
        hyprctl reload
        notify-send "Monitor Config Restored"
        exit 0
        ;;
esac

# Write and Reload
if [ -n "$NEW_CONFIG" ]; then
    echo -e "$NEW_CONFIG" > "$CONFIG_FILE"
    hyprctl reload
    
    # Restart interface components to ensure they move to the active monitor
    killall waybar
    waybar &
    
    # Reload wallpaper daemon if running
    if pgrep -x "swww-daemon" > /dev/null; then
        CURRENT_WALL=$(swww query | grep -oP 'image: \K.*' | head -n 1)
        if [ -n "$CURRENT_WALL" ]; then
            swww img "$CURRENT_WALL" --transition-type none &
        fi
    fi
    
    notify-send "Monitor config updated & reloaded"
fi